# LAMBDA
* IT IS USED TO COMPRESS THE PROGRAM
* IT IS FUNCTION
* SYNTAX: a=lambda x,y:x+y

In [1]:
a=lambda x,y:x+y
a(9,9)

18

In [2]:
b=lambda x:x**2
b(6)

36

In [4]:
# program to print a table using string comprehension
n=int(input("enter n value"))
m=10
b=1
a=[n*i for i in range(b,m+1)]
a

enter n value6


[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]

# LIST COMPREHENSION:
* 

# FILE HANDLING
* performming operations in a file is called file handling
* entering some data into a file is called as write to a file-w
* retriving data from a file is called as reading from a file-r
* entering additional data to th e
* we can perform append,delete,operations in file

In [9]:
# creating and entering data into file
def writetoafile(filename,data):
    with open (filename,"w") as f:
        f.write(data)
    return
filename = "samplefile.txt"
writetoafile(filename,"hii\nsmaple file created successfully\nthank you!")

In [14]:
# opening the file and retreving data from that file.
def readfromafile(filename):
    with open (filename,"r") as f:
        fd=f.read()
        f.close()
    return fd
readfromafile("samplefile.txt")

'hii\nsmaple file created successfully\nthank you!'

In [19]:
# to get output in seperate lines with out \n
def readfromafile(filename):
    with open (filename,"r") as f:
        fd=f.read()
        f.close()
    return fd
filename="samplefile.txt"
readfromafile("samplefile.txt")
def printlines(filename):
    with open (filename,"r") as f:
        for line in f:
            print(line,end=" ")
        return
printlines(filename)

hii
 smaple file created successfully
 thank you! 

In [6]:
def writetoafile(filename,data):
    with open (filename,"w") as f:
        f.write(data)
    return
filename = "programfile.txt"
writetoafile(filename,"n=int(input('enter n value'))\nm=10\nb=1\na=[n*i for i in range(b,m+1)]\na")
def readfromafile(filename):
    with open (filename,"r") as f:
        fd=f.read()
        f.close()
    return fd
filename="programfile.txt"
readfromafile("programfile.txt")
def printlines(filename):
    with open (filename,"r") as f:
        for line in f:
            print(line,end=" ")
        return
printlines(filename)


n=int(input('enter n value'))
 m=10
 b=1
 a=[n*i for i in range(b,m+1)]
 a 

In [7]:
def appendtofile(filename,data):
    with open(filename,"a") as f:
        for line in data:
            f.write("\n"+line)
        return
data=["additional data","added successfully"]
filename="samplefile.txt"
appendtofile(filename,data)

# NUMPY-NUMERICAL PYTHON
* IT IS USED TO PERFORM ARTHEMATICAL,STSTISTICAL OPERATIONS
* IT IS AN ADVANCED PYTHON LIBRARY,
* PERFORMANCE SPEED IS HIGH AND TIME SAVING AND LESS MEMORY ACCESSING ARE ADVANTAGES 
* REPRESENTATION OF VALUES IN NUMPY IS IN THE FORM OF ROWS AND COLUMNS(array)
* TO IMPORT NUMPY : IMPORT NUMPY

In [3]:
import numpy as np
a=np.array([1,2,3,4])           # one dimensional array
a

array([1, 2, 3, 4])

In [4]:
a=np.arange(1,11)
a                            # areating an array using particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# for checking the number of elements
a.size

10

In [9]:
a+1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [10]:
a-1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a2=np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [51]:
a3 = np.array([[1,2,3,4],[5,6,7,8]])
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
a3[0]

array([1, 2, 3, 4])

In [52]:
a3[0:1,1:2]  #a[startingrow:ending row,startingcolumn:endingcolumn]

array([[2]])

In [53]:
a3[:,1:3]

array([[2, 3],
       [6, 7]])

In [54]:
a3[:,2:3]

array([[3],
       [7]])

In [55]:
a3[:,0:2]

array([[1, 2],
       [5, 6]])

In [57]:
a3.shape

(2, 4)

In [58]:
a3.ndim

2

In [61]:
a3.itemsize

4

In [18]:
a2.dtype

dtype('complex128')

In [26]:
# comparision of two arrays
a1=np.array([[1,2,3,4],[9,8,7,6]])
b1=np.array([[2,4,5,6],[7,9,6,0]])
a1>b1

array([[False, False, False, False],
       [ True, False,  True,  True]])

In [27]:
a1<b1

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [29]:
a1==a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a1+b1

array([[ 3.+0.j,  6.+0.j,  8.+0.j, 10.+0.j],
       [12.+0.j, 15.+0.j, 13.+0.j,  8.+0.j]])

In [36]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [40]:
np.ones([5,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### by using arange create two dimensional array?

In [60]:
i=0
j=4
for i in range(2):
    rss=np.arange(i, j)
    i+=1
    j+=1
    print(np.array(rss))

[0 1 2 3]
[1 2 3 4]


In [70]:
# reshaping the given array
b1=np.arange(1,11)

In [72]:
b1.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [74]:
max(b1)

10

In [75]:
min(b1)

1

In [76]:
np.std(b1)

2.8722813232690143

In [77]:
np.sum(b1)

55

In [78]:
np.var(b1)

8.25

In [80]:
np.cumsum(b1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [81]:
np.argmin(b1)

0

In [83]:
np.argmax(b1)

9

In [84]:
np.transpose(b1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
b=int(input("enter binary number:"))  # binary to decimal conversion
d=0
i=0
while(b!=0):
    decimal=b%10
    d=d+decimal*(2**i)
    b=b//10
    i=i+1
print(d)
    
    
    

enter binary number:1110011
115


In [ ]:
d=int(input("enter decimal number:"))  # decimal to binary conversion
